### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by xMicz**
Update partner.json

### CODE REVIEW

**Comment by mipcit1010** [comment]
Wdym?

**Comment by xMicz** [comment]
{
  "partners": [
    {
      "code": "513946525426",
      "ownerID": "615029465726320654",
      "icon": "https://codeshare.xyz/public/img/logo.png",
      "serverName": "Code Share",
      "website": "https://codeshare.xyz",
      "description": "The right place to share your own personal codes and find the code you are looking for.."
    },

**Comment by mipcit1010** [comment]
What's wrong with it?

**Comment by Evo-Pro** [comment]
We are sorry but, if you want to be one of our partners, please contact us via discord, make sure to read partnering rules.

**Comment by mipcit1010** [comment]
Hey, sorry for that, What's wrong with it?

**Pull request closed without merging**
